name: My First GitHub Action  # Workflow name

on: push  # This workflow runs on every push to the repository

jobs:
  say-hello:
    runs-on: ubuntu-latest  # Uses an Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Pulls your repo's code

      - name: Print a message
        run: echo "Hello, GitHub Actions!"
